Create corpus model
dhmit/gender_analysis_web pull request #18
Opened 2021-06-25 21:01 UTC by yaroluchko

This PR creates the basic corpus model that we can work on and add functionality to.

2021-06-28 00:55 UTC, sharabhuiyan approved these changes
Good job! The testing seems fine and I really liked how you guys utilized many to many relationships.

2021-06-28 00:55 UTC, sharabhuiyan commented on backend/app/models.py
> +    corpuses = models.ManyToManyField(Corpus)
I really like this! This is a really neat way to keep track of documents in Corpora.

2021-06-28 00:55 UTC, sharabhuiyan commented on backend/app/tests.py
> +        self.assertEqual(doc_1.words_associated('his'), Counter({'cigarette': 1, 'speech': 1}))
Also consider making a test case with "her" because it also appears a few times in this document.

2021-06-29 10:52 UTC, MBJean requested changes
This pretty much looks good to me, thanks for your review, Shara! One thing, though: are the changes in `texts.py` intentional? They all concern the `Document` model, and look duplicative of what's in the `DocumentTestCase` class above.

2021-07-09 20:16 UTC, phuang00 commented
We fixed the duplicate test cases in `tests.py` and we added test cases to ensure that we can properly associate the `corpus` and `document` models.

2021-07-09 20:33 UTC, YifanWang0 commented
We also created a Corpus serializer.

2021-07-10 19:17 UTC, MBJean approved these changes
This generally looks good, thanks! I have two pieces of feedback below. Let me know what you think, and if you agree, they should be easy changes to make, so I'll leave my approval here.

1. We'll want to manually add the plural `corpora` to our `Corpus` model. You can do so by following the guidelines outlined [here](https://books.agiliq.com/projects/django-admin-cookbook/en/latest/plural_text.html). Otherwise, we'll end up in a weird situation, as we already are in with `PronounSeries`, where we get a silly plural name `Corpuss` and `PronounSeriess`, respectively. See this screencap of the admin page without manually specifying the plural:

<img width="289" alt="Screen Shot 2021-07-10 at 3 01 57 PM" src="https://user-images.githubusercontent.com/20114078/125174189-96b6c500-e191-11eb-9f09-d2cf1a5acad8.png">

2. I'm thinking that the `ManyToMany` field should be specified on the `Corpus` model, not the `Document` model. That's my impulse because I'm imaging that a user is going to create a `Corpus` in the UI, then pick which `Document`s to add via a dropdown or something. In other words, the user will be working in the context of a `Corpus`, not a `Document`, when adding `Document`s to a `Corpus`, and so adding the `ManyToMany` field to `Corpus` more accurately reflects that behavior. [An old version of the Django docs](https://docs.djangoproject.com/en/1.8/topics/db/models/#many-to-many-relationships) recommends as such, as well.

2021-07-10 21:01 UTC, phuang00 commented
> 2. I'm thinking that the `ManyToMany` field should be specified on the `Corpus` model, not the `Document` model. That's my impulse because I'm imaging that a user is going to create a `Corpus` in the UI, then pick which `Document`s to add via a dropdown or something. In other words, the user will be working in the context of a `Corpus`, not a `Document`, when adding `Document`s to a `Corpus`, and so adding the `ManyToMany` field to `Corpus` more accurately reflects that behavior. [An old version of the Django docs](https://docs.djangoproject.com/en/1.8/topics/db/models/#many-to-many-relationships) recommends as such, as well.

@MBJean 
We were also looking at the Django docs when we were writing the `ManyToMany` field and the [docs](https://docs.djangoproject.com/en/3.2/topics/db/examples/many_to_many/) had the opposite convention so we followed that even thought it seemed counterintuitive. Which Django docs should we follow?

2021-07-10 21:11 UTC, MBJean commented
Good call out. I think the doc you linked is perhaps just not particularly specific. In the general models docs ([here's](https://docs.djangoproject.com/en/3.2/topics/db/models/#many-to-many-relationships) a more updated link than what I first posted above), the example of Pizza and Topping models has the ManyToMany field on Pizza. That seems to correspond to our use case here. What do you think?

2021-07-10 21:15 UTC, phuang00 commented
Yeah, I think the ManyToMany field for Pizza and Topping makes more sense intuitively and match with what we're doing. We'll update the field!

2021-07-10 21:26 UTC, merged